---
- hosts: all
  sudo: true
  vars:
    web_server: apachephp
    servername: myApp.vb www.myApp.vb 192.168.33.113
    timezone: Asia/Tokyo
  vars_files:
    - vars/mariadb.yml
    - vars/common.yml
    - [ "vars/apachephp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php7-cli
    - apache
    - php7
    - mariadb
    - composer
    - phpcommon
    - app
